config/routes.rb
Catz::Application.routes.draw do
  devise_for :users

  root :to => 'pages#index'

  match 'pages/:id' => 'pages#view'

  resources :users, :only => [:index, :show] do
    resources :cats , :only => [:index]
    get :liked_cats, :on => :member
    member do 
      post :follow
      delete :unfollow
    end
  end

  resources :cats do
    member do
      post :like
      delete :unlike
    end  
  end 

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :user_name, :first_name, :last_name, :city, :age,  :password, :password_confirmation, :remember_me, :image
  validates_presence_of :first_name,:last_name, :email, :user_name, :city, :age
  validates_uniqueness_of :email

  mount_uploader :image, ImageUploader

  before_validation :ensure_last_name_and_username

  #Cat likes stuff
  has_many :cats, :dependent => :destroy
  has_many :likes
  has_many :liked_cats, :through => :likes, :source => :cat

  #Follow stuff
  has_many :following_users, class_name: 'Follow', foreign_key: 'followed_user_id'
  has_many :followers, through: :following_users, source: :follower
  has_many :followings, class_name: 'Follow', foreign_key: 'user_id'
  has_many :users_followed, through: :followings, source: :followed_user

  SHOW_TOP_CATS_LIMIT = 3




  def ensure_last_name_and_username
    self.last_name = "Doe" if last_name.blank?
    self.user_name = "theuser" if user_name.blank?
  end



  def owns?(cat)
    cat.user == self
  end 

  def is_followed_by?(user)
    followers.include? user
  end

  def is_following?(user)
    users_followed.include? user
  end

  def unfollow!(user)
    followers.delete(user) if is_followed_by?(user)
  end

  def follow!(user)
    followers << user unless is_followed_by?(user)
  end

  def fullname
    "#{first_name} #{last_name}"  
  end

  def to_s
    fullname
  end

  def likes?(cat)
    liked_cats.include? cat
  end

  def like!(cat)
    liked_cats << cat unless likes?(cat)
  end

  def unlike!(cat)
    liked_cats.delete(cat) if likes?(cat)
  end

  def top_cats
    cats.limit(SHOW_TOP_CATS_LIMIT)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_user, :only => [:show, :liked_cats, :follow, :unfollow]
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @following_me = @user.followers
    @followed_by_me = @user.users_followed
  end

  def liked_cats
    @liked_cats = @user.liked_cats
  end

  def follow
    @user.follow!(current_user)
    redirect_to :back, notice: "You followed #{@user}"
  end

  def unfollow
    @user.unfollow!(current_user)
    redirect_to :back, notice: "You un-followed #{@user}"    
  end

  private
    def load_user
      if params[:id]
        @user = User.find(params[:id])        
      else    
        @user = current_user
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper

	def follow_button(user)
        if user.is_followed_by?(current_user)
           link_to "Unfollow", unfollow_user_path(user), method: :delete, class: 'button radius small alert'
        else
           link_to "Follow", follow_user_path(user), method: :post, class: 'button radius small'
        end  		
	end
end

app/views/users/index.html.erb
<h1>Listing users</h1>
<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>User name</th>
    <th>Email</th>
    <th>City</th>
    <th>Age</th>
    <th>His cats</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.user_name %></td>
    <td><%= user.email %></td>
    <td><%= user.city %></td>
    <td><%= user.age %></td>
    <td><%= link_to user.cats.count, user_cats_path(user) %></td>
    <td><%= link_to 'Show', user %></td>
    <td>
        <% if can? :follow, @user %>
            <%=follow_button @user %>
        <% end %>  
    </td>
  </tr>
<% end %>
</table>

app/views/users/liked_cats.html.erb
<h1><%=@user%>'s Favorite pussies</h1>

<%= render '/cats/cat_list' , :cats => @liked_cats %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>User name:</b>
  <%= @user.user_name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>City:</b>
  <%= @user.city %>
</p>

<p>
  <b>Age:</b>
  <%= @user.age %>
</p>

<%= image_tag @user.image, width: 200, height: 200 %><br/>

<%= link_to 'Back', users_path %> <br>
<%= link_to 'He has ' +  @user.cats.count.to_s + ' cats', user_cats_path(@user) %> | 
<%= link_to 'He likes ' + @user.liked_cats.count.to_s + ' cats', liked_cats_user_path(@user) %>
<br>
<% #binding.pry %>
<% if can? :follow, @user %>
  <%=follow_button @user %>
<% end %>  
<hr>
<h2>User's cats</h2>

<%= render '/cats/cat_list', :cats => @user.top_cats %>
<% if @user.cats.size > User::SHOW_TOP_CATS_LIMIT %>
  <%= link_to "See all #{@user}'s cat", user_cats_path(@user) %>
<% elsif (@user.cats.size == 0) %>
  <%=@user%> has no cats, you should suggest him upload some
<% end %>  

<hr>
<h2>People that follow <%=@user!=current_user ? "#{@user}" : 'me'%></h2>
<% @following_me.each do |follower| %>
  <p><%= link_to follower==current_user ? 'You are' : "#{follower} is", follower %> following <%=@user!=current_user ? @user : 'you' %></p>
<% end %>
<hr>   
<h2>People that <%=@user!=current_user ? "#{@user} follows" : 'I follow'%></h2>
<% @followed_by_me.each do |followed| %>
  <p><%=@user!=current_user ? "#{@user} follows" : 'You follow' %> <%= link_to followed, followed %></p>
<% end %>