config/routes.rb
Catz::Application.routes.draw do
  devise_for :users

  root :to => 'pages#index'

  match 'pages/:id' => 'pages#view'

  resources :users, :only => [:index, :show] do
    resources :cats , :only => [:index]
    get :liked_cats, :on => :member
    member do 
      post :follow
      delete :unfollow
    end
  end

  resources :cats do
    member do
      post :like
      delete :unlike
    end  
  end 

end

app/models/cat.rb
class Cat < ActiveRecord::Base

  BREED_TYPES = ['Abyssinian', 'Aegean cat', 'Bengal', 'Burmese', 'Cymric', 'Havana Brown', 'Unknown']
  attr_accessible :bio, :name, :breed, :image
  mount_uploader :image, ImageUploader
  validates_presence_of :name, :user_id

  belongs_to :user

  has_many :likes

  has_many :likers, :through => :likes, :source => :user

  validates :breed, :inclusion => {:in => Cat::BREED_TYPES}

  default_scope { order('cats.created_at desc') }
  
  scope :by_breed, lambda { |breed| where('breed = ?', breed) }

  #Different approach to :by_bread
  BREED_TYPES.each do |breed|
    scope breed.gsub(' ','_').downcase.to_sym, lambda { where(breed: breed) }
  end 

  def self.not_owned_by(user)
    user ? where('user_id <> ?', user.id) : scoped
  end

  def liked_by?(user)
    likers.include? user
  end  

  def catname
    "#{name}" 
  end

  def to_s
    catname
  end

  def likes_count
    likes.size
  end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_cat, :only => [:edit, :show, :update, :destroy]
  before_filter :load_user, :only => [:index] 
  #before_filter :authorize_cat!, :only => [:edit, :update, :destroy]
  load_and_authorize_resource

  # GET /user/cats
  def index
    @cats = @user.cats  
  end

  # GET /cats/1
  def show
    
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats
  def create
    @cat = current_user.cats.new(params[:cat])
    
      if @cat.save
        flash[:notice] = "Created cat successfully"
        redirect_to @cat
      else
        render action: "new"
      end
  end

  # PUT /cats/1
  def update
      if @cat.update_attributes(params[:cat])
        redirect_to @cat, notice: 'Cat was successfully updated.'
      else
        render action: "edit"
      end
  end

  # DELETE /cats/1
  def destroy
    if @cat
      if @cat.destroy
        redirect_to cats_url, notice: 'Cat was deleted successfully'
      else
        flash[:alert] = 'Run. We have a zombie cat'
        redirect_to cats_url 
      end  
    else
        redirect_to cats_url, alert: 'Cat does not exist'
    end    
  end

 def like
   @cat = Cat.find(params[:id])
   current_user.like!(@cat)
   CatMailer.new_like(@cat, current_user).deliver
   redirect_to :back, notice: "You liked #{@cat}"
 end

def unlike
   @cat = Cat.find(params[:id])
   current_user.unlike!(@cat)
   CatMailer.new_unlike(@cat, current_user).deliver
   redirect_to :back, notice: "You un-liked #{@cat}"
 end

private
  def load_cat
      @cat = Cat.find(params[:id])
  end

  def load_user
    if params[:user_id]
      @user = User.find(params[:user_id])        
    else    
      @user = current_user
    end
  end

  def authorize_cat!
    deny unless current_user.owns?(@cat)
  end

end

app/helpers/cats_helper.rb
module CatsHelper

	def like_button(cat)
        if cat.liked_by?(current_user)
           link_to "Unlike", unlike_cat_path(cat), method: :delete, class: 'button radius small alert'
        else
           link_to "Like", like_cat_path(cat), method: :post, class: 'button radius small'
        end  		
	end

end

app/views/cats/_cat_list.html.erb
    <ul class="small-block-grid-2 large-block-grid-4">
      <% cats.each do |cat| %>
        <li>
          <div class="panel callout feed-item">
            <div class="cat-image">
              <%= image_tag cat.image, width: 200, height: 200 %>
            </div>
            <div class="cat-details">  
              <h3><%= cat.name %></h3>
              <p><%= cat.bio %></p>
            </div>
            <div class="cat-links">
              <%=like_button cat %>
              <% if can? :update, cat %>
                <%= link_to 'Edit', edit_cat_path(cat), style: 'margin-right: 20px' %>
                <%= link_to 'Destroy', cat, method: :delete, 'data-confirm' => 'Are you sure?' %>
              <% end %>
              <br/>
              <span>(<b><%=cat.likes_count %></b> People like him)</span>
            </div>  
          </div>
        </li>
      <% end %>
    </ul>

app/views/cats/_form.html.erb
<%= simple_form_for @cat do |f| %>
    <%= f.input :name, label: 'Cat\'s name', placeholder: 'The name of your pussy' %>
    <%= f.input :breed, :collection => Cat::BREED_TYPES %>
    <%= f.input :bio %>
    <%= f.input :image %> 
    <%= image_tag cat.image, width: 400, height: 400 unless cat.image.blank? %><br/>
    <%= f.submit 'Save', class: 'button' %>
<% end %>

app/views/cats/edit.html.erb
<h1>Editing cat</h1>

<%= render 'form' , :cat => @cat %>

<%= link_to 'Show', @cat %> |
<%= link_to 'Back', cats_path %>

app/views/cats/index.html.erb
<h2><%= @user %>'s cats</h2>
<%= render 'cat_list', :cats => @cats %>

<%= link_to 'New Cat', new_cat_path %>

app/views/cats/new.html.erb
<h1>New cat</h1>

<%= render 'form', cat: @cat %>

<%= link_to 'Back', cats_path %>

app/views/cats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @cat.name %>
</p>

<p>
  <b>Bio:</b>
  <%= @cat.bio %>
</p>

<p>
	<%= image_tag @cat.image, width: 200, height: 200 %>
</p>	


<%= link_to 'Edit', edit_cat_path(@cat) %> |
<%= link_to 'Back', cats_path %>